openapi: 3.0.0
info:
  title: Booking Api XML
  version: '1.0'
servers:
  - url: 'https://www.utazzitthon.hu/api'
paths:
  /availbility:
    post:
      summary: ''
      operationId: post-availbility
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: |
                order
        description: ''
components:
  schemas: {}
